name: ğŸ£ğŸ¥š

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    if: github.repository == 'luxass/luxass.dev' && github.event.issue.user.login == 'luxass' && contains(github.event.issue.labels.*.name, 'easter-ğŸ¥š')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say Hello!
        run: echo "Hello ${{ github.event.issue.user.login }}!"
